### ISSUE TITLE
Class constructor Command cannot be invoked without 'new'

### ISSUE THREAD

**Issue by BinaryMuse** [arcanis/clipanion#10]
I'm unable to get a very basic setup working, although when I clone the repo and run the tests everything seems fine.

## Reproduction Steps

(Using npm instead of Yarn here to reduce variables)

```
mkdir clip-test && cd clip-test
npm init -y
npm i clipanion typescript ts-node @types/node
curl https://gist.githubusercontent.com/BinaryMuse/bbb9bdb6f3c4658838792fb44926b8f2/raw/284dbb07157100215a0d7914e9e5e4f285f17ef9/tsconfig.json -o tsconfig.json
curl https://gist.githubusercontent.com/BinaryMuse/bbb9bdb6f3c4658838792fb44926b8f2/raw/284dbb07157100215a0d7914e9e5e4f285f17ef9/index.ts -o index.ts
./node_modules/.bin/ts-node index.ts
```

Here's the Gist with the two files: https://gist.github.com/BinaryMuse/bbb9bdb6f3c4658838792fb44926b8f2

## Error

```
$ ./node_modules/.bin/ts-node index.ts
Type Error: Class constructor Command cannot be invoked without 'new'
    at new CommandHelp (/Users/mtilley/src/clip-test/index.ts:62:42)
    at Cli.process (/Users/mtilley/src/clip-test/node_modules/clipanion/lib/advanced/Cli.js:47:37)
    at Cli.run (/Users/mtilley/src/clip-test/node_modules/clipanion/lib/advanced/Cli.js:64:32)
    at Cli.runExit (/Users/mtilley/src/clip-test/node_modules/clipanion/lib/advanced/Cli.js:94:39)
    at Object.<anonymous> (/Users/mtilley/src/clip-test/index.ts:16:5)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Module.m._compile (/Users/mtilley/src/clip-test/node_modules/ts-node/src/index.ts:814:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/mtilley/src/clip-test/node_modules/ts-node/src/index.ts:817:12)
    at Module.load (internal/modules/cjs/loader.js:812:32)
```

**Comment by arcanis** [comment]
Interesting - it seems the problem comes from `"target": "es5"`, as it works with `es2015` 🤔

**Comment by BinaryMuse** [comment]
> Interesting - it seems the problem comes from `"target": "es5"`, as it works with `es2015` 🤔

Oh interesting, you are right! I didn't think to try this. 🙈

This is a good enough solution for me, so happy to have this issue closed, unless you prefer to leave it open :)

**Comment by mtiller** [comment]
I'm not sure this issue should be closed.  I tripped over the same thing.  If it is considered unreasonable to use `es5` (which is the default from `tsc --init .`), then perhaps you could perform some kind of test at the start to see if the code was generated with that target (*e.g.,* by see if this error gets triggered) and then informing the user.  Otherwise, you'll have new uses constantly tripping over this.
