### ISSUE TITLE
Some issues getting example code working

### ISSUE THREAD

**Issue by reggi** [arcanis/clipanion#44]
I dumped the example code and tried running it and had some issues:

```bash
➜  agnostic git:(master) ✗ ts-node ./packages/cerba/example.ts greet --name 'hi' 
Type Error: Class constructor Command cannot be invoked without 'new'
    at new GreetCommand (/Users/thomas/Desktop/agnostic/packages/cerba/example.ts:5:1)
    at Cli.process (/Users/thomas/Desktop/agnostic/node_modules/clipanion/lib/index.js:1194:37)
    at Cli.run (/Users/thomas/Desktop/agnostic/node_modules/clipanion/lib/index.js:1210:32)
    at Cli.runExit (/Users/thomas/Desktop/agnostic/node_modules/clipanion/lib/index.js:1252:39)
    at Object.<anonymous> (/Users/thomas/Desktop/agnostic/packages/cerba/example.ts:50:5)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Module.m._compile (/Users/thomas/.config/yarn/global/node_modules/ts-node/src/index.ts:814:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/thomas/.config/yarn/global/node_modules/ts-node/src/index.ts:817:12)
    at Module.load (internal/modules/cjs/loader.js:985:32)
```

**Comment by cncshaggy** [comment]
I've gotten this before too, what is your target in your tsconfig? it's probably too low

**Comment by reggi** [comment]
@cncshaggy es5 i believe

**Comment by cncshaggy** [comment]
try `es2018`

**Comment by arcanis** [comment]
Closing since we don't use decorators anymore.
